name: SonarCloud

on: [push]

jobs:
  sonar:
    name: sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SonarCloud
        run: mvn verify sonar:sonar
        env:
          SONAR_TOKEN: a1063d00ce6ba9aa5fe576fb9444c3392c18a34f
          GITHUB_TOKEN: 7b31e3bde0b32afc11f62690d21a057a47679657